// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users_control_tower.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminUsersOverview = `-- name: AdminUsersOverview :one
WITH base AS (
    SELECT
        u.clerk_id,
        u.role,
        u.is_active,
        u.last_login_at,
        COALESCE(hm.hospital_id, 0)::bigint AS membership_hospital_id,
        COALESCE(hm.membership_role, '')::text AS membership_role,
        COALESCE(h.is_active, FALSE) AS membership_hospital_active
    FROM users u
    LEFT JOIN hospital_memberships hm
        ON hm.user_clerk_id = u.clerk_id
       AND hm.is_active = TRUE
       AND hm.deleted_at IS NULL
    LEFT JOIN hospitals h
        ON h.id = hm.hospital_id
       AND h.deleted_at IS NULL
    WHERE u.deleted_at IS NULL
)
SELECT
    COUNT(*)::bigint AS total_users,
    COUNT(*) FILTER (WHERE is_active = TRUE)::bigint AS active_users,
    COUNT(*) FILTER (WHERE is_active = FALSE)::bigint AS inactive_users,
    COUNT(*) FILTER (WHERE role <> 'superadmin' AND membership_hospital_id = 0)::bigint AS unassigned_users,
    COUNT(*) FILTER (WHERE role = 'admin' AND membership_role <> 'admin')::bigint AS admin_role_mismatch_users,
    COUNT(*) FILTER (WHERE is_active = FALSE AND membership_hospital_id > 0)::bigint AS inactive_with_membership_users,
    COUNT(*) FILTER (WHERE membership_hospital_id > 0 AND membership_hospital_active = FALSE)::bigint AS assigned_inactive_hospital_users,
    COUNT(*) FILTER (WHERE last_login_at IS NULL)::bigint AS never_logged_in_users
FROM base
`

type AdminUsersOverviewRow struct {
	TotalUsers                    int64 `json:"total_users"`
	ActiveUsers                   int64 `json:"active_users"`
	InactiveUsers                 int64 `json:"inactive_users"`
	UnassignedUsers               int64 `json:"unassigned_users"`
	AdminRoleMismatchUsers        int64 `json:"admin_role_mismatch_users"`
	InactiveWithMembershipUsers   int64 `json:"inactive_with_membership_users"`
	AssignedInactiveHospitalUsers int64 `json:"assigned_inactive_hospital_users"`
	NeverLoggedInUsers            int64 `json:"never_logged_in_users"`
}

func (q *Queries) AdminUsersOverview(ctx context.Context) (AdminUsersOverviewRow, error) {
	row := q.db.QueryRow(ctx, adminUsersOverview)
	var i AdminUsersOverviewRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.InactiveUsers,
		&i.UnassignedUsers,
		&i.AdminRoleMismatchUsers,
		&i.InactiveWithMembershipUsers,
		&i.AssignedInactiveHospitalUsers,
		&i.NeverLoggedInUsers,
	)
	return i, err
}

const countAdminUsersSearch = `-- name: CountAdminUsersSearch :one
WITH base AS (
    SELECT
        u.clerk_id,
        u.name,
        COALESCE(u.email, '')::text AS email,
        COALESCE(u.username, '')::text AS username,
        u.role,
        u.is_active,
        u.last_login_at,
        COALESCE(hm.hospital_id, 0)::bigint AS membership_hospital_id,
        COALESCE(h.slug, '')::text AS membership_hospital_slug,
        COALESCE(hm.membership_role, '')::text AS membership_role,
        (u.role <> 'superadmin' AND COALESCE(hm.hospital_id, 0) = 0)::boolean AS anomaly_no_membership,
        (u.role = 'admin' AND COALESCE(hm.membership_role, '') <> 'admin')::boolean AS anomaly_admin_role_mismatch,
        (u.is_active = FALSE AND COALESCE(hm.hospital_id, 0) > 0)::boolean AS anomaly_inactive_with_membership,
        (COALESCE(hm.hospital_id, 0) > 0 AND COALESCE(h.is_active, FALSE) = FALSE)::boolean AS anomaly_assigned_inactive_hospital,
        (u.last_login_at IS NULL)::boolean AS anomaly_never_logged_in
    FROM users u
    LEFT JOIN hospital_memberships hm
        ON hm.user_clerk_id = u.clerk_id
       AND hm.is_active = TRUE
       AND hm.deleted_at IS NULL
    LEFT JOIN hospitals h
        ON h.id = hm.hospital_id
       AND h.deleted_at IS NULL
    WHERE u.deleted_at IS NULL
)
SELECT COUNT(*)::bigint
FROM base
WHERE
    ($1::text = ''
        OR base.clerk_id ILIKE '%' || $1 || '%'
        OR base.name ILIKE '%' || $1 || '%'
        OR base.email ILIKE '%' || $1 || '%'
        OR base.username ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR base.role = $2)
    AND (
        $3::text = ''
        OR ($3::text = 'active' AND base.is_active = TRUE)
        OR ($3::text = 'inactive' AND base.is_active = FALSE)
    )
    AND ($4::text = '' OR base.membership_hospital_slug = $4)
    AND ($5::text = '' OR base.membership_role = $5)
    AND (
        $6::text = ''
        OR ($6::text = 'no_membership' AND base.anomaly_no_membership)
        OR ($6::text = 'admin_role_mismatch' AND base.anomaly_admin_role_mismatch)
        OR ($6::text = 'inactive_with_membership' AND base.anomaly_inactive_with_membership)
        OR ($6::text = 'assigned_inactive_hospital' AND base.anomaly_assigned_inactive_hospital)
        OR ($6::text = 'never_logged_in' AND base.anomaly_never_logged_in)
    )
    AND (
        $7::text = ''
        OR ($7::text = 'never' AND base.last_login_at IS NULL)
        OR ($7::text = 'gt_30d' AND base.last_login_at < NOW() - INTERVAL '30 days')
        OR ($7::text = 'gt_90d' AND base.last_login_at < NOW() - INTERVAL '90 days')
        OR ($7::text = 'gt_180d' AND base.last_login_at < NOW() - INTERVAL '180 days')
        OR ($7::text = 'recent_30d' AND base.last_login_at >= NOW() - INTERVAL '30 days')
    )
`

type CountAdminUsersSearchParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Column6 string `json:"column_6"`
	Column7 string `json:"column_7"`
}

func (q *Queries) CountAdminUsersSearch(ctx context.Context, arg CountAdminUsersSearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsersSearch,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deactivateHospitalMembershipByUser = `-- name: DeactivateHospitalMembershipByUser :execrows
UPDATE hospital_memberships
SET
    is_active = FALSE,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE user_clerk_id = $1
  AND is_active = TRUE
  AND deleted_at IS NULL
`

func (q *Queries) DeactivateHospitalMembershipByUser(ctx context.Context, userClerkID string) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateHospitalMembershipByUser, userClerkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveHospitalMembershipContextByUser = `-- name: GetActiveHospitalMembershipContextByUser :one
SELECT
    hm.hospital_id,
    hm.membership_role,
    h.slug AS hospital_slug,
    h.is_active AS hospital_is_active
FROM hospital_memberships hm
JOIN hospitals h ON h.id = hm.hospital_id
WHERE hm.user_clerk_id = $1
  AND hm.is_active = TRUE
  AND hm.deleted_at IS NULL
  AND h.deleted_at IS NULL
LIMIT 1
`

type GetActiveHospitalMembershipContextByUserRow struct {
	HospitalID       int64  `json:"hospital_id"`
	MembershipRole   string `json:"membership_role"`
	HospitalSlug     string `json:"hospital_slug"`
	HospitalIsActive bool   `json:"hospital_is_active"`
}

func (q *Queries) GetActiveHospitalMembershipContextByUser(ctx context.Context, userClerkID string) (GetActiveHospitalMembershipContextByUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveHospitalMembershipContextByUser, userClerkID)
	var i GetActiveHospitalMembershipContextByUserRow
	err := row.Scan(
		&i.HospitalID,
		&i.MembershipRole,
		&i.HospitalSlug,
		&i.HospitalIsActive,
	)
	return i, err
}

const getAdminUserDetail = `-- name: GetAdminUserDetail :one
SELECT
    u.clerk_id,
    u.name,
    COALESCE(u.email, '')::text AS email,
    COALESCE(u.username, '')::text AS username,
    COALESCE(u.first_name, '')::text AS first_name,
    COALESCE(u.last_name, '')::text AS last_name,
    u.role,
    u.is_active,
    u.created_at,
    u.updated_at,
    u.last_login_at,
    COALESCE(hm.hospital_id, 0)::bigint AS membership_hospital_id,
    COALESCE(h.slug, '')::text AS membership_hospital_slug,
    COALESCE(h.name, '')::text AS membership_hospital_name,
    COALESCE(h.is_active, FALSE) AS membership_hospital_active,
    COALESCE(hm.membership_role, '')::text AS membership_role,
    (u.role <> 'superadmin' AND COALESCE(hm.hospital_id, 0) = 0)::boolean AS anomaly_no_membership,
    (u.role = 'admin' AND COALESCE(hm.membership_role, '') <> 'admin')::boolean AS anomaly_admin_role_mismatch,
    (u.is_active = FALSE AND COALESCE(hm.hospital_id, 0) > 0)::boolean AS anomaly_inactive_with_membership,
    (COALESCE(hm.hospital_id, 0) > 0 AND COALESCE(h.is_active, FALSE) = FALSE)::boolean AS anomaly_assigned_inactive_hospital,
    (u.last_login_at IS NULL)::boolean AS anomaly_never_logged_in
FROM users u
LEFT JOIN hospital_memberships hm
    ON hm.user_clerk_id = u.clerk_id
   AND hm.is_active = TRUE
   AND hm.deleted_at IS NULL
LEFT JOIN hospitals h
    ON h.id = hm.hospital_id
   AND h.deleted_at IS NULL
WHERE u.clerk_id = $1
  AND u.deleted_at IS NULL
`

type GetAdminUserDetailRow struct {
	ClerkID                         string             `json:"clerk_id"`
	Name                            string             `json:"name"`
	Email                           string             `json:"email"`
	Username                        string             `json:"username"`
	FirstName                       string             `json:"first_name"`
	LastName                        string             `json:"last_name"`
	Role                            string             `json:"role"`
	IsActive                        bool               `json:"is_active"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt                     pgtype.Timestamptz `json:"last_login_at"`
	MembershipHospitalID            int64              `json:"membership_hospital_id"`
	MembershipHospitalSlug          string             `json:"membership_hospital_slug"`
	MembershipHospitalName          string             `json:"membership_hospital_name"`
	MembershipHospitalActive        bool               `json:"membership_hospital_active"`
	MembershipRole                  string             `json:"membership_role"`
	AnomalyNoMembership             bool               `json:"anomaly_no_membership"`
	AnomalyAdminRoleMismatch        bool               `json:"anomaly_admin_role_mismatch"`
	AnomalyInactiveWithMembership   bool               `json:"anomaly_inactive_with_membership"`
	AnomalyAssignedInactiveHospital bool               `json:"anomaly_assigned_inactive_hospital"`
	AnomalyNeverLoggedIn            bool               `json:"anomaly_never_logged_in"`
}

func (q *Queries) GetAdminUserDetail(ctx context.Context, clerkID string) (GetAdminUserDetailRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserDetail, clerkID)
	var i GetAdminUserDetailRow
	err := row.Scan(
		&i.ClerkID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.MembershipHospitalID,
		&i.MembershipHospitalSlug,
		&i.MembershipHospitalName,
		&i.MembershipHospitalActive,
		&i.MembershipRole,
		&i.AnomalyNoMembership,
		&i.AnomalyAdminRoleMismatch,
		&i.AnomalyInactiveWithMembership,
		&i.AnomalyAssignedInactiveHospital,
		&i.AnomalyNeverLoggedIn,
	)
	return i, err
}

const getHospitalBySlugForUpdate = `-- name: GetHospitalBySlugForUpdate :one
SELECT
    id,
    name,
    slug,
    is_active,
    created_by_clerk_id,
    created_at,
    updated_at,
    deleted_at
FROM hospitals
WHERE slug = $1
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetHospitalBySlugForUpdate(ctx context.Context, slug string) (Hospital, error) {
	row := q.db.QueryRow(ctx, getHospitalBySlugForUpdate, slug)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedByClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByClerkIDForUpdate = `-- name: GetUserByClerkIDForUpdate :one
SELECT
    clerk_id,
    name,
    role,
    is_active,
    deleted_at
FROM users
WHERE clerk_id = $1
FOR UPDATE
`

type GetUserByClerkIDForUpdateRow struct {
	ClerkID   string             `json:"clerk_id"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByClerkIDForUpdate(ctx context.Context, clerkID string) (GetUserByClerkIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserByClerkIDForUpdate, clerkID)
	var i GetUserByClerkIDForUpdateRow
	err := row.Scan(
		&i.ClerkID,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const insertAdminUserAction = `-- name: InsertAdminUserAction :exec
INSERT INTO admin_user_actions (
    actor_clerk_id,
    target_clerk_id,
    action_type,
    reason,
    before_state,
    after_state,
    metadata,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type InsertAdminUserActionParams struct {
	ActorClerkID  string `json:"actor_clerk_id"`
	TargetClerkID string `json:"target_clerk_id"`
	ActionType    string `json:"action_type"`
	Reason        string `json:"reason"`
	BeforeState   []byte `json:"before_state"`
	AfterState    []byte `json:"after_state"`
	Metadata      []byte `json:"metadata"`
}

func (q *Queries) InsertAdminUserAction(ctx context.Context, arg InsertAdminUserActionParams) error {
	_, err := q.db.Exec(ctx, insertAdminUserAction,
		arg.ActorClerkID,
		arg.TargetClerkID,
		arg.ActionType,
		arg.Reason,
		arg.BeforeState,
		arg.AfterState,
		arg.Metadata,
	)
	return err
}

const listAdminUserActionsByTarget = `-- name: ListAdminUserActionsByTarget :many
SELECT
    id,
    actor_clerk_id,
    target_clerk_id,
    action_type,
    reason,
    before_state,
    after_state,
    metadata,
    created_at
FROM admin_user_actions
WHERE target_clerk_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAdminUserActionsByTargetParams struct {
	TargetClerkID string `json:"target_clerk_id"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) ListAdminUserActionsByTarget(ctx context.Context, arg ListAdminUserActionsByTargetParams) ([]AdminUserAction, error) {
	rows, err := q.db.Query(ctx, listAdminUserActionsByTarget, arg.TargetClerkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminUserAction
	for rows.Next() {
		var i AdminUserAction
		if err := rows.Scan(
			&i.ID,
			&i.ActorClerkID,
			&i.TargetClerkID,
			&i.ActionType,
			&i.Reason,
			&i.BeforeState,
			&i.AfterState,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHospitalsForAdminUsers = `-- name: ListHospitalsForAdminUsers :many
SELECT
    id,
    name,
    slug,
    is_active
FROM hospitals
WHERE deleted_at IS NULL
ORDER BY is_active DESC, name ASC, id ASC
`

type ListHospitalsForAdminUsersRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) ListHospitalsForAdminUsers(ctx context.Context) ([]ListHospitalsForAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listHospitalsForAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHospitalsForAdminUsersRow
	for rows.Next() {
		var i ListHospitalsForAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAdminUsers = `-- name: SearchAdminUsers :many
WITH base AS (
    SELECT
        u.clerk_id,
        u.name,
        COALESCE(u.email, '')::text AS email,
        COALESCE(u.username, '')::text AS username,
        COALESCE(u.first_name, '')::text AS first_name,
        COALESCE(u.last_name, '')::text AS last_name,
        u.role,
        u.is_active,
        u.created_at,
        u.updated_at,
        u.last_login_at,
        COALESCE(hm.hospital_id, 0)::bigint AS membership_hospital_id,
        COALESCE(h.slug, '')::text AS membership_hospital_slug,
        COALESCE(h.name, '')::text AS membership_hospital_name,
        COALESCE(h.is_active, FALSE) AS membership_hospital_active,
        COALESCE(hm.membership_role, '')::text AS membership_role,
        (u.role <> 'superadmin' AND COALESCE(hm.hospital_id, 0) = 0)::boolean AS anomaly_no_membership,
        (u.role = 'admin' AND COALESCE(hm.membership_role, '') <> 'admin')::boolean AS anomaly_admin_role_mismatch,
        (u.is_active = FALSE AND COALESCE(hm.hospital_id, 0) > 0)::boolean AS anomaly_inactive_with_membership,
        (COALESCE(hm.hospital_id, 0) > 0 AND COALESCE(h.is_active, FALSE) = FALSE)::boolean AS anomaly_assigned_inactive_hospital,
        (u.last_login_at IS NULL)::boolean AS anomaly_never_logged_in
    FROM users u
    LEFT JOIN hospital_memberships hm
        ON hm.user_clerk_id = u.clerk_id
       AND hm.is_active = TRUE
       AND hm.deleted_at IS NULL
    LEFT JOIN hospitals h
        ON h.id = hm.hospital_id
       AND h.deleted_at IS NULL
    WHERE u.deleted_at IS NULL
)
SELECT
    clerk_id,
    name,
    email,
    username,
    first_name,
    last_name,
    role,
    is_active,
    created_at,
    updated_at,
    last_login_at,
    membership_hospital_id,
    membership_hospital_slug,
    membership_hospital_name,
    membership_hospital_active,
    membership_role,
    anomaly_no_membership,
    anomaly_admin_role_mismatch,
    anomaly_inactive_with_membership,
    anomaly_assigned_inactive_hospital,
    anomaly_never_logged_in
FROM base
WHERE
    ($1::text = ''
        OR base.clerk_id ILIKE '%' || $1 || '%'
        OR base.name ILIKE '%' || $1 || '%'
        OR base.email ILIKE '%' || $1 || '%'
        OR base.username ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR base.role = $2)
    AND (
        $3::text = ''
        OR ($3::text = 'active' AND base.is_active = TRUE)
        OR ($3::text = 'inactive' AND base.is_active = FALSE)
    )
    AND ($4::text = '' OR base.membership_hospital_slug = $4)
    AND ($5::text = '' OR base.membership_role = $5)
    AND (
        $6::text = ''
        OR ($6::text = 'no_membership' AND base.anomaly_no_membership)
        OR ($6::text = 'admin_role_mismatch' AND base.anomaly_admin_role_mismatch)
        OR ($6::text = 'inactive_with_membership' AND base.anomaly_inactive_with_membership)
        OR ($6::text = 'assigned_inactive_hospital' AND base.anomaly_assigned_inactive_hospital)
        OR ($6::text = 'never_logged_in' AND base.anomaly_never_logged_in)
    )
    AND (
        $7::text = ''
        OR ($7::text = 'never' AND base.last_login_at IS NULL)
        OR ($7::text = 'gt_30d' AND base.last_login_at < NOW() - INTERVAL '30 days')
        OR ($7::text = 'gt_90d' AND base.last_login_at < NOW() - INTERVAL '90 days')
        OR ($7::text = 'gt_180d' AND base.last_login_at < NOW() - INTERVAL '180 days')
        OR ($7::text = 'recent_30d' AND base.last_login_at >= NOW() - INTERVAL '30 days')
    )
ORDER BY base.created_at DESC, base.clerk_id DESC
LIMIT $8 OFFSET $9
`

type SearchAdminUsersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Column6 string `json:"column_6"`
	Column7 string `json:"column_7"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchAdminUsersRow struct {
	ClerkID                         string             `json:"clerk_id"`
	Name                            string             `json:"name"`
	Email                           string             `json:"email"`
	Username                        string             `json:"username"`
	FirstName                       string             `json:"first_name"`
	LastName                        string             `json:"last_name"`
	Role                            string             `json:"role"`
	IsActive                        bool               `json:"is_active"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt                     pgtype.Timestamptz `json:"last_login_at"`
	MembershipHospitalID            int64              `json:"membership_hospital_id"`
	MembershipHospitalSlug          string             `json:"membership_hospital_slug"`
	MembershipHospitalName          string             `json:"membership_hospital_name"`
	MembershipHospitalActive        bool               `json:"membership_hospital_active"`
	MembershipRole                  string             `json:"membership_role"`
	AnomalyNoMembership             bool               `json:"anomaly_no_membership"`
	AnomalyAdminRoleMismatch        bool               `json:"anomaly_admin_role_mismatch"`
	AnomalyInactiveWithMembership   bool               `json:"anomaly_inactive_with_membership"`
	AnomalyAssignedInactiveHospital bool               `json:"anomaly_assigned_inactive_hospital"`
	AnomalyNeverLoggedIn            bool               `json:"anomaly_never_logged_in"`
}

func (q *Queries) SearchAdminUsers(ctx context.Context, arg SearchAdminUsersParams) ([]SearchAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, searchAdminUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAdminUsersRow
	for rows.Next() {
		var i SearchAdminUsersRow
		if err := rows.Scan(
			&i.ClerkID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.MembershipHospitalID,
			&i.MembershipHospitalSlug,
			&i.MembershipHospitalName,
			&i.MembershipHospitalActive,
			&i.MembershipRole,
			&i.AnomalyNoMembership,
			&i.AnomalyAdminRoleMismatch,
			&i.AnomalyInactiveWithMembership,
			&i.AnomalyAssignedInactiveHospital,
			&i.AnomalyNeverLoggedIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
