// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hospital_memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveHospitalMembershipByUser = `-- name: GetActiveHospitalMembershipByUser :one
SELECT
  hospital_id,
  membership_role
FROM hospital_memberships
WHERE user_clerk_id = $1
  AND is_active = TRUE
  AND deleted_at IS NULL
`

type GetActiveHospitalMembershipByUserRow struct {
	HospitalID     int64  `json:"hospital_id"`
	MembershipRole string `json:"membership_role"`
}

func (q *Queries) GetActiveHospitalMembershipByUser(ctx context.Context, userClerkID string) (GetActiveHospitalMembershipByUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveHospitalMembershipByUser, userClerkID)
	var i GetActiveHospitalMembershipByUserRow
	err := row.Scan(&i.HospitalID, &i.MembershipRole)
	return i, err
}

const hasActiveAdminMembership = `-- name: HasActiveAdminMembership :one
SELECT EXISTS (
  SELECT 1
  FROM hospital_memberships hm
  JOIN hospitals h ON h.id = hm.hospital_id
  WHERE hm.user_clerk_id = $1
    AND hm.membership_role = 'admin'
    AND hm.is_active = TRUE
    AND hm.deleted_at IS NULL
    AND h.is_active = TRUE
    AND h.deleted_at IS NULL
) AS has_admin_membership
`

func (q *Queries) HasActiveAdminMembership(ctx context.Context, userClerkID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAdminMembership, userClerkID)
	var has_admin_membership bool
	err := row.Scan(&has_admin_membership)
	return has_admin_membership, err
}

const hasActiveHospitalMembership = `-- name: HasActiveHospitalMembership :one
SELECT EXISTS (
  SELECT 1
  FROM hospital_memberships hm
  JOIN hospitals h ON h.id = hm.hospital_id
  WHERE hm.user_clerk_id = $1
    AND hm.is_active = TRUE
    AND hm.deleted_at IS NULL
    AND h.is_active = TRUE
    AND h.deleted_at IS NULL
) AS has_membership
`

func (q *Queries) HasActiveHospitalMembership(ctx context.Context, userClerkID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveHospitalMembership, userClerkID)
	var has_membership bool
	err := row.Scan(&has_membership)
	return has_membership, err
}

const upsertHospitalUserMembership = `-- name: UpsertHospitalUserMembership :exec
INSERT INTO hospital_memberships (
    hospital_id,
    user_clerk_id,
    membership_role,
    is_active,
    invited_by_clerk_id,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, TRUE, $4, NOW(), NOW())
ON CONFLICT (user_clerk_id) DO UPDATE
SET hospital_id = EXCLUDED.hospital_id,
    membership_role = EXCLUDED.membership_role,
    is_active = TRUE,
    invited_by_clerk_id = EXCLUDED.invited_by_clerk_id,
    deleted_at = NULL,
    updated_at = NOW()
`

type UpsertHospitalUserMembershipParams struct {
	HospitalID       int64       `json:"hospital_id"`
	UserClerkID      string      `json:"user_clerk_id"`
	MembershipRole   string      `json:"membership_role"`
	InvitedByClerkID pgtype.Text `json:"invited_by_clerk_id"`
}

func (q *Queries) UpsertHospitalUserMembership(ctx context.Context, arg UpsertHospitalUserMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertHospitalUserMembership,
		arg.HospitalID,
		arg.UserClerkID,
		arg.MembershipRole,
		arg.InvitedByClerkID,
	)
	return err
}
