// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hospital_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeHospitalInvite = `-- name: ConsumeHospitalInvite :execrows
UPDATE hospital_invites
SET consumed_at = NOW(),
    consumed_by_clerk_id = $2
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
`

type ConsumeHospitalInviteParams struct {
	ID                int64       `json:"id"`
	ConsumedByClerkID pgtype.Text `json:"consumed_by_clerk_id"`
}

func (q *Queries) ConsumeHospitalInvite(ctx context.Context, arg ConsumeHospitalInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeHospitalInvite, arg.ID, arg.ConsumedByClerkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createHospitalInvite = `-- name: CreateHospitalInvite :one
INSERT INTO hospital_invites (
    hospital_id,
    token_hash,
    invite_role,
    created_by_clerk_id,
    expires_at,
    created_at
)
VALUES ($1, $2, 'user', $3, $4, NOW())
RETURNING id, hospital_id, token_hash, invite_role, created_by_clerk_id, expires_at, consumed_at, consumed_by_clerk_id, created_at
`

type CreateHospitalInviteParams struct {
	HospitalID       int64              `json:"hospital_id"`
	TokenHash        string             `json:"token_hash"`
	CreatedByClerkID string             `json:"created_by_clerk_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHospitalInvite(ctx context.Context, arg CreateHospitalInviteParams) (HospitalInvite, error) {
	row := q.db.QueryRow(ctx, createHospitalInvite,
		arg.HospitalID,
		arg.TokenHash,
		arg.CreatedByClerkID,
		arg.ExpiresAt,
	)
	var i HospitalInvite
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.TokenHash,
		&i.InviteRole,
		&i.CreatedByClerkID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedByClerkID,
		&i.CreatedAt,
	)
	return i, err
}

const getHospitalInviteByTokenHash = `-- name: GetHospitalInviteByTokenHash :one
SELECT
  hi.id,
  hi.hospital_id,
  hi.token_hash,
  hi.invite_role,
  hi.created_by_clerk_id,
  hi.expires_at,
  hi.consumed_at,
  hi.consumed_by_clerk_id,
  hi.created_at,
  h.is_active AS hospital_is_active,
  h.deleted_at AS hospital_deleted_at
FROM hospital_invites hi
JOIN hospitals h ON h.id = hi.hospital_id
WHERE hi.token_hash = $1
`

type GetHospitalInviteByTokenHashRow struct {
	ID                int64              `json:"id"`
	HospitalID        int64              `json:"hospital_id"`
	TokenHash         string             `json:"token_hash"`
	InviteRole        string             `json:"invite_role"`
	CreatedByClerkID  string             `json:"created_by_clerk_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	ConsumedByClerkID pgtype.Text        `json:"consumed_by_clerk_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	HospitalIsActive  bool               `json:"hospital_is_active"`
	HospitalDeletedAt pgtype.Timestamptz `json:"hospital_deleted_at"`
}

func (q *Queries) GetHospitalInviteByTokenHash(ctx context.Context, tokenHash string) (GetHospitalInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getHospitalInviteByTokenHash, tokenHash)
	var i GetHospitalInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.TokenHash,
		&i.InviteRole,
		&i.CreatedByClerkID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedByClerkID,
		&i.CreatedAt,
		&i.HospitalIsActive,
		&i.HospitalDeletedAt,
	)
	return i, err
}

const listHospitalInvitesBySlug = `-- name: ListHospitalInvitesBySlug :many
SELECT
  hi.id,
  hi.hospital_id,
  hi.invite_role,
  hi.created_by_clerk_id,
  hi.expires_at,
  hi.consumed_at,
  hi.consumed_by_clerk_id,
  hi.created_at
FROM hospital_invites hi
JOIN hospitals h ON h.id = hi.hospital_id
WHERE h.slug = $1
  AND h.deleted_at IS NULL
ORDER BY hi.created_at DESC, hi.id DESC
`

type ListHospitalInvitesBySlugRow struct {
	ID                int64              `json:"id"`
	HospitalID        int64              `json:"hospital_id"`
	InviteRole        string             `json:"invite_role"`
	CreatedByClerkID  string             `json:"created_by_clerk_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	ConsumedByClerkID pgtype.Text        `json:"consumed_by_clerk_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListHospitalInvitesBySlug(ctx context.Context, slug string) ([]ListHospitalInvitesBySlugRow, error) {
	rows, err := q.db.Query(ctx, listHospitalInvitesBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHospitalInvitesBySlugRow
	for rows.Next() {
		var i ListHospitalInvitesBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.InviteRole,
			&i.CreatedByClerkID,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ConsumedByClerkID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
