// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hospitals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignHospitalAdmin = `-- name: AssignHospitalAdmin :exec
INSERT INTO hospital_memberships (
    hospital_id,
    user_clerk_id,
    membership_role,
    is_active,
    invited_by_clerk_id,
    created_at,
    updated_at
)
VALUES ($1, $2, 'admin', TRUE, $3, NOW(), NOW())
ON CONFLICT (user_clerk_id) DO UPDATE
SET hospital_id = EXCLUDED.hospital_id,
    membership_role = EXCLUDED.membership_role,
    is_active = TRUE,
    invited_by_clerk_id = EXCLUDED.invited_by_clerk_id,
    deleted_at = NULL,
    updated_at = NOW()
`

type AssignHospitalAdminParams struct {
	HospitalID       int64       `json:"hospital_id"`
	UserClerkID      string      `json:"user_clerk_id"`
	InvitedByClerkID pgtype.Text `json:"invited_by_clerk_id"`
}

func (q *Queries) AssignHospitalAdmin(ctx context.Context, arg AssignHospitalAdminParams) error {
	_, err := q.db.Exec(ctx, assignHospitalAdmin, arg.HospitalID, arg.UserClerkID, arg.InvitedByClerkID)
	return err
}

const createHospital = `-- name: CreateHospital :one
INSERT INTO hospitals (name, slug, created_by_clerk_id, is_active, created_at, updated_at)
VALUES ($1, $2, $3, TRUE, NOW(), NOW())
RETURNING id, name, slug, is_active, created_by_clerk_id, created_at, updated_at, deleted_at
`

type CreateHospitalParams struct {
	Name             string `json:"name"`
	Slug             string `json:"slug"`
	CreatedByClerkID string `json:"created_by_clerk_id"`
}

func (q *Queries) CreateHospital(ctx context.Context, arg CreateHospitalParams) (Hospital, error) {
	row := q.db.QueryRow(ctx, createHospital, arg.Name, arg.Slug, arg.CreatedByClerkID)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedByClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateHospitalAdminMembership = `-- name: DeactivateHospitalAdminMembership :execrows
UPDATE hospital_memberships
SET
  is_active = FALSE,
  deleted_at = NOW(),
  updated_at = NOW()
WHERE hospital_id = $1
  AND user_clerk_id = $2
  AND membership_role = 'admin'
  AND is_active = TRUE
  AND deleted_at IS NULL
`

type DeactivateHospitalAdminMembershipParams struct {
	HospitalID  int64  `json:"hospital_id"`
	UserClerkID string `json:"user_clerk_id"`
}

func (q *Queries) DeactivateHospitalAdminMembership(ctx context.Context, arg DeactivateHospitalAdminMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateHospitalAdminMembership, arg.HospitalID, arg.UserClerkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHospitalByID = `-- name: GetHospitalByID :one
SELECT id, name, slug, is_active, created_by_clerk_id, created_at, updated_at, deleted_at
FROM hospitals
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetHospitalByID(ctx context.Context, id int64) (Hospital, error) {
	row := q.db.QueryRow(ctx, getHospitalByID, id)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedByClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHospitalBySlug = `-- name: GetHospitalBySlug :one
SELECT id, name, slug, is_active, created_by_clerk_id, created_at, updated_at, deleted_at
FROM hospitals
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetHospitalBySlug(ctx context.Context, slug string) (Hospital, error) {
	row := q.db.QueryRow(ctx, getHospitalBySlug, slug)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedByClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdminAssignmentCandidates = `-- name: ListAdminAssignmentCandidates :many
SELECT
  u.clerk_id,
  u.name,
  COALESCE(u.email, '')::text AS email,
  COALESCE(u.username, '')::text AS username,
  u.role,
  u.is_active,
  COALESCE(hm.hospital_id, 0)::bigint AS membership_hospital_id,
  COALESCE(hm.membership_role, '')::text AS membership_role,
  COALESCE(hm.is_active, FALSE) AS membership_is_active,
  COALESCE(hm_h.slug, '')::text AS membership_hospital_slug
FROM users u
LEFT JOIN hospital_memberships hm
  ON hm.user_clerk_id = u.clerk_id
 AND hm.is_active = TRUE
 AND hm.deleted_at IS NULL
LEFT JOIN hospitals hm_h ON hm_h.id = hm.hospital_id
WHERE u.deleted_at IS NULL
  AND u.role <> 'superadmin'
ORDER BY u.created_at DESC, u.clerk_id DESC
`

type ListAdminAssignmentCandidatesRow struct {
	ClerkID                string `json:"clerk_id"`
	Name                   string `json:"name"`
	Email                  string `json:"email"`
	Username               string `json:"username"`
	Role                   string `json:"role"`
	IsActive               bool   `json:"is_active"`
	MembershipHospitalID   int64  `json:"membership_hospital_id"`
	MembershipRole         string `json:"membership_role"`
	MembershipIsActive     bool   `json:"membership_is_active"`
	MembershipHospitalSlug string `json:"membership_hospital_slug"`
}

func (q *Queries) ListAdminAssignmentCandidates(ctx context.Context) ([]ListAdminAssignmentCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAdminAssignmentCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminAssignmentCandidatesRow
	for rows.Next() {
		var i ListAdminAssignmentCandidatesRow
		if err := rows.Scan(
			&i.ClerkID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.IsActive,
			&i.MembershipHospitalID,
			&i.MembershipRole,
			&i.MembershipIsActive,
			&i.MembershipHospitalSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHospitalAdminsBySlug = `-- name: ListHospitalAdminsBySlug :many
SELECT
  u.clerk_id,
  u.name,
  COALESCE(u.email, '')::text AS email,
  COALESCE(u.username, '')::text AS username,
  hm.created_at AS assigned_at
FROM hospital_memberships hm
JOIN hospitals h ON h.id = hm.hospital_id
JOIN users u ON u.clerk_id = hm.user_clerk_id
WHERE h.slug = $1
  AND h.deleted_at IS NULL
  AND hm.membership_role = 'admin'
  AND hm.is_active = TRUE
  AND hm.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY hm.created_at DESC, u.clerk_id DESC
`

type ListHospitalAdminsBySlugRow struct {
	ClerkID    string             `json:"clerk_id"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	Username   string             `json:"username"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ListHospitalAdminsBySlug(ctx context.Context, slug string) ([]ListHospitalAdminsBySlugRow, error) {
	rows, err := q.db.Query(ctx, listHospitalAdminsBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHospitalAdminsBySlugRow
	for rows.Next() {
		var i ListHospitalAdminsBySlugRow
		if err := rows.Scan(
			&i.ClerkID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHospitalUsersBySlug = `-- name: ListHospitalUsersBySlug :many
SELECT
  u.clerk_id,
  u.name,
  COALESCE(u.email, '')::text AS email,
  COALESCE(u.username, '')::text AS username,
  COALESCE(u.first_name, '')::text AS first_name,
  COALESCE(u.last_name, '')::text AS last_name,
  u.role,
  hm.membership_role,
  u.is_active,
  u.created_at,
  u.updated_at,
  u.last_login_at
FROM hospital_memberships hm
JOIN hospitals h ON h.id = hm.hospital_id
JOIN users u ON u.clerk_id = hm.user_clerk_id
WHERE h.slug = $1
  AND h.deleted_at IS NULL
  AND hm.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY hm.created_at DESC, u.clerk_id DESC
`

type ListHospitalUsersBySlugRow struct {
	ClerkID        string             `json:"clerk_id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Username       string             `json:"username"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Role           string             `json:"role"`
	MembershipRole string             `json:"membership_role"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListHospitalUsersBySlug(ctx context.Context, slug string) ([]ListHospitalUsersBySlugRow, error) {
	rows, err := q.db.Query(ctx, listHospitalUsersBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHospitalUsersBySlugRow
	for rows.Next() {
		var i ListHospitalUsersBySlugRow
		if err := rows.Scan(
			&i.ClerkID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.MembershipRole,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHospitals = `-- name: ListHospitals :many
SELECT id, name, slug, is_active, created_by_clerk_id, created_at, updated_at, deleted_at
FROM hospitals
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListHospitals(ctx context.Context) ([]Hospital, error) {
	rows, err := q.db.Query(ctx, listHospitals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hospital
	for rows.Next() {
		var i Hospital
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedByClerkID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
