// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Hospital struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	IsActive         bool               `json:"is_active"`
	CreatedByClerkID string             `json:"created_by_clerk_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type HospitalInvite struct {
	ID                int64              `json:"id"`
	HospitalID        int64              `json:"hospital_id"`
	TokenHash         string             `json:"token_hash"`
	InviteRole        string             `json:"invite_role"`
	CreatedByClerkID  string             `json:"created_by_clerk_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	ConsumedByClerkID pgtype.Text        `json:"consumed_by_clerk_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type HospitalMembership struct {
	ID               int64              `json:"id"`
	HospitalID       int64              `json:"hospital_id"`
	UserClerkID      string             `json:"user_clerk_id"`
	MembershipRole   string             `json:"membership_role"`
	IsActive         bool               `json:"is_active"`
	InvitedByClerkID pgtype.Text        `json:"invited_by_clerk_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ClerkID     string             `json:"clerk_id"`
	Name        string             `json:"name"`
	Email       pgtype.Text        `json:"email"`
	Username    pgtype.Text        `json:"username"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Role        string             `json:"role"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	FirstName   pgtype.Text        `json:"first_name"`
	LastName    pgtype.Text        `json:"last_name"`
}
