// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AdminUsersOverview(ctx context.Context) (AdminUsersOverviewRow, error)
	AssignHospitalAdmin(ctx context.Context, arg AssignHospitalAdminParams) error
	ConsumeHospitalInvite(ctx context.Context, arg ConsumeHospitalInviteParams) (int64, error)
	CountAdminUsersSearch(ctx context.Context, arg CountAdminUsersSearchParams) (int64, error)
	CreateHospital(ctx context.Context, arg CreateHospitalParams) (Hospital, error)
	CreateHospitalInvite(ctx context.Context, arg CreateHospitalInviteParams) (CreateHospitalInviteRow, error)
	DeactivateHospitalAdminMembership(ctx context.Context, arg DeactivateHospitalAdminMembershipParams) (int64, error)
	DeactivateHospitalMembershipByUser(ctx context.Context, userClerkID string) (int64, error)
	DeleteUserByClerkID(ctx context.Context, clerkID string) error
	GetActiveHospitalMembershipByUser(ctx context.Context, userClerkID string) (GetActiveHospitalMembershipByUserRow, error)
	GetActiveHospitalMembershipContextByUser(ctx context.Context, userClerkID string) (GetActiveHospitalMembershipContextByUserRow, error)
	GetAdminUserDetail(ctx context.Context, clerkID string) (GetAdminUserDetailRow, error)
	GetHospitalByID(ctx context.Context, id int64) (Hospital, error)
	GetHospitalBySlug(ctx context.Context, slug string) (Hospital, error)
	GetHospitalBySlugForUpdate(ctx context.Context, slug string) (Hospital, error)
	GetHospitalInviteByIDForUpdate(ctx context.Context, arg GetHospitalInviteByIDForUpdateParams) (GetHospitalInviteByIDForUpdateRow, error)
	GetHospitalInviteByTokenHash(ctx context.Context, tokenHash string) (GetHospitalInviteByTokenHashRow, error)
	GetUserAuthContext(ctx context.Context, clerkID string) (GetUserAuthContextRow, error)
	GetUserByClerkID(ctx context.Context, clerkID string) (GetUserByClerkIDRow, error)
	GetUserByClerkIDForUpdate(ctx context.Context, clerkID string) (GetUserByClerkIDForUpdateRow, error)
	GetUserRole(ctx context.Context, clerkID string) (string, error)
	HasActiveAdminMembership(ctx context.Context, userClerkID string) (bool, error)
	HasActiveHospitalMembership(ctx context.Context, userClerkID string) (bool, error)
	InsertAdminUserAction(ctx context.Context, arg InsertAdminUserActionParams) error
	ListAdminAssignmentCandidates(ctx context.Context) ([]ListAdminAssignmentCandidatesRow, error)
	ListAdminUserActionsByTarget(ctx context.Context, arg ListAdminUserActionsByTargetParams) ([]AdminUserAction, error)
	ListHospitalAdminsBySlug(ctx context.Context, slug string) ([]ListHospitalAdminsBySlugRow, error)
	ListHospitalInvitesBySlug(ctx context.Context, slug string) ([]ListHospitalInvitesBySlugRow, error)
	ListHospitalUsersBySlug(ctx context.Context, slug string) ([]ListHospitalUsersBySlugRow, error)
	ListHospitals(ctx context.Context) ([]Hospital, error)
	ListHospitalsForAdminUsers(ctx context.Context) ([]ListHospitalsForAdminUsersRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RevokeHospitalInvite(ctx context.Context, arg RevokeHospitalInviteParams) (int64, error)
	SearchAdminUsers(ctx context.Context, arg SearchAdminUsersParams) ([]SearchAdminUsersRow, error)
	SetUserActiveByClerkID(ctx context.Context, arg SetUserActiveByClerkIDParams) error
	SetUserRoleByClerkID(ctx context.Context, arg SetUserRoleByClerkIDParams) error
	SoftDeleteUserByClerkID(ctx context.Context, clerkID string) error
	UpdateLastLogin(ctx context.Context, clerkID string) error
	UpsertHospitalUserMembership(ctx context.Context, arg UpsertHospitalUserMembershipParams) error
	UpsertUserWithRole(ctx context.Context, arg UpsertUserWithRoleParams) error
}

var _ Querier = (*Queries)(nil)
