// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteUserByClerkID(ctx context.Context, clerkID string) error
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	SoftDeleteUserByClerkID(ctx context.Context, clerkID string) error
	UpdateLastLogin(ctx context.Context, clerkID string) error
	UpsertUserWithRole(ctx context.Context, arg UpsertUserWithRoleParams) error
}

var _ Querier = (*Queries)(nil)
