// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserByClerkID = `-- name: DeleteUserByClerkID :exec
DELETE FROM users WHERE clerk_id = $1
`

func (q *Queries) DeleteUserByClerkID(ctx context.Context, clerkID string) error {
	_, err := q.db.Exec(ctx, deleteUserByClerkID, clerkID)
	return err
}

const getUserAuthContext = `-- name: GetUserAuthContext :one
SELECT
  u.clerk_id,
  u.role AS global_role,
  u.is_active,
  COALESCE(hm.hospital_id, 0)::bigint AS hospital_id,
  COALESCE(hm.membership_role, '')::text AS membership_role
FROM users u
LEFT JOIN LATERAL (
  SELECT hm.hospital_id, hm.membership_role
  FROM hospital_memberships hm
  JOIN hospitals h ON h.id = hm.hospital_id
  WHERE hm.user_clerk_id = u.clerk_id
    AND hm.is_active = TRUE
    AND hm.deleted_at IS NULL
    AND h.is_active = TRUE
    AND h.deleted_at IS NULL
  LIMIT 1
) hm ON TRUE
WHERE u.clerk_id = $1
  AND u.is_active = TRUE
  AND u.deleted_at IS NULL
`

type GetUserAuthContextRow struct {
	ClerkID        string `json:"clerk_id"`
	GlobalRole     string `json:"global_role"`
	IsActive       bool   `json:"is_active"`
	HospitalID     int64  `json:"hospital_id"`
	MembershipRole string `json:"membership_role"`
}

func (q *Queries) GetUserAuthContext(ctx context.Context, clerkID string) (GetUserAuthContextRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthContext, clerkID)
	var i GetUserAuthContextRow
	err := row.Scan(
		&i.ClerkID,
		&i.GlobalRole,
		&i.IsActive,
		&i.HospitalID,
		&i.MembershipRole,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT
  clerk_id,
  name,
  role,
  is_active,
  deleted_at
FROM users
WHERE clerk_id = $1
`

type GetUserByClerkIDRow struct {
	ClerkID   string             `json:"clerk_id"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (GetUserByClerkIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i GetUserByClerkIDRow
	err := row.Scan(
		&i.ClerkID,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users WHERE clerk_id = $1 AND is_active = TRUE AND deleted_at IS NULL
`

func (q *Queries) GetUserRole(ctx context.Context, clerkID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, clerkID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    COALESCE(clerk_id, '')::text      AS clerk_id,
    name,
    COALESCE(email, '')::text         AS email,
    COALESCE(username, '')::text      AS username,
    COALESCE(first_name, '')::text    AS first_name,
    COALESCE(last_name, '')::text     AS last_name,
    role,
    is_active,
    created_at,
    updated_at,
    deleted_at,
    last_login_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC, clerk_id DESC
`

type ListUsersRow struct {
	ClerkID     string             `json:"clerk_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Username    string             `json:"username"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Role        string             `json:"role"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ClerkID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActiveByClerkID = `-- name: SetUserActiveByClerkID :exec
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE clerk_id = $1
`

type SetUserActiveByClerkIDParams struct {
	ClerkID  string `json:"clerk_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) SetUserActiveByClerkID(ctx context.Context, arg SetUserActiveByClerkIDParams) error {
	_, err := q.db.Exec(ctx, setUserActiveByClerkID, arg.ClerkID, arg.IsActive)
	return err
}

const setUserRoleByClerkID = `-- name: SetUserRoleByClerkID :exec
UPDATE users
SET role = $2, updated_at = NOW()
WHERE clerk_id = $1
`

type SetUserRoleByClerkIDParams struct {
	ClerkID string `json:"clerk_id"`
	Role    string `json:"role"`
}

func (q *Queries) SetUserRoleByClerkID(ctx context.Context, arg SetUserRoleByClerkIDParams) error {
	_, err := q.db.Exec(ctx, setUserRoleByClerkID, arg.ClerkID, arg.Role)
	return err
}

const softDeleteUserByClerkID = `-- name: SoftDeleteUserByClerkID :exec
UPDATE users
SET deleted_at = NOW(), is_active = FALSE, updated_at = NOW()
WHERE clerk_id = $1
`

func (q *Queries) SoftDeleteUserByClerkID(ctx context.Context, clerkID string) error {
	_, err := q.db.Exec(ctx, softDeleteUserByClerkID, clerkID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW(), updated_at = NOW()
WHERE clerk_id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, clerkID string) error {
	_, err := q.db.Exec(ctx, updateLastLogin, clerkID)
	return err
}

const upsertUserWithRole = `-- name: UpsertUserWithRole :exec
INSERT INTO users (clerk_id, username, name, email, first_name, last_name, role, is_active, created_at, updated_at)
VALUES (
  $1, $2, $3, $4, $5, $6,
  CASE WHEN NOT EXISTS (SELECT 1 FROM users WHERE deleted_at IS NULL)
       THEN 'superadmin'
       ELSE 'user'
  END,
  CASE WHEN NOT EXISTS (SELECT 1 FROM users WHERE deleted_at IS NULL)
       THEN TRUE
       ELSE FALSE
  END,
  NOW(), NOW()
)
ON CONFLICT (clerk_id) DO UPDATE
SET username   = EXCLUDED.username,
    name       = EXCLUDED.name,
    first_name = EXCLUDED.first_name,
    last_name  = EXCLUDED.last_name,
    email      = COALESCE(EXCLUDED.email, users.email),
    is_active  = CASE
                   WHEN users.role = 'superadmin' THEN TRUE
                   WHEN EXISTS (
                     SELECT 1
                     FROM hospital_memberships hm
                     JOIN hospitals h ON h.id = hm.hospital_id
                     WHERE hm.user_clerk_id = users.clerk_id
                       AND hm.is_active = TRUE
                       AND hm.deleted_at IS NULL
                       AND h.is_active = TRUE
                       AND h.deleted_at IS NULL
                   ) THEN TRUE
                   ELSE FALSE
                 END,
    deleted_at = NULL,
    updated_at = NOW()
`

type UpsertUserWithRoleParams struct {
	ClerkID   string      `json:"clerk_id"`
	Username  pgtype.Text `json:"username"`
	Name      string      `json:"name"`
	Email     pgtype.Text `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}

func (q *Queries) UpsertUserWithRole(ctx context.Context, arg UpsertUserWithRoleParams) error {
	_, err := q.db.Exec(ctx, upsertUserWithRole,
		arg.ClerkID,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	return err
}
