// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserByClerkID = `-- name: DeleteUserByClerkID :exec
DELETE FROM users WHERE clerk_id = $1
`

func (q *Queries) DeleteUserByClerkID(ctx context.Context, clerkID string) error {
	_, err := q.db.Exec(ctx, deleteUserByClerkID, clerkID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT
    COALESCE(clerk_id, '')::text      AS clerk_id,
    name,
    COALESCE(email, '')::text         AS email,
    COALESCE(username, '')::text      AS username,
    role,
    is_active,
    created_at,
    updated_at,
    deleted_at,
    last_login_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC, clerk_id DESC
`

type ListUsersRow struct {
	ClerkID     string             `json:"clerk_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Username    string             `json:"username"`
	Role        string             `json:"role"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ClerkID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUserByClerkID = `-- name: SoftDeleteUserByClerkID :exec
UPDATE users
SET deleted_at = NOW(), is_active = FALSE, updated_at = NOW()
WHERE clerk_id = $1
`

func (q *Queries) SoftDeleteUserByClerkID(ctx context.Context, clerkID string) error {
	_, err := q.db.Exec(ctx, softDeleteUserByClerkID, clerkID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW(), updated_at = NOW()
WHERE clerk_id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, clerkID string) error {
	_, err := q.db.Exec(ctx, updateLastLogin, clerkID)
	return err
}

const upsertUserWithRole = `-- name: UpsertUserWithRole :exec
INSERT INTO users (clerk_id, username, name, email, role, is_active, created_at, updated_at)
VALUES (
  $1, $2, $3, $4,
  CASE WHEN NOT EXISTS (SELECT 1 FROM users WHERE deleted_at IS NULL)
       THEN 'superadmin'
       ELSE 'user'
  END,
  TRUE, NOW(), NOW()
)
ON CONFLICT (clerk_id) DO UPDATE
SET username   = EXCLUDED.username,
    name       = EXCLUDED.name,
    email      = COALESCE(EXCLUDED.email, users.email),
    is_active  = TRUE,
    deleted_at = NULL,
    updated_at = NOW()
`

type UpsertUserWithRoleParams struct {
	ClerkID  string      `json:"clerk_id"`
	Username pgtype.Text `json:"username"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) UpsertUserWithRole(ctx context.Context, arg UpsertUserWithRoleParams) error {
	_, err := q.db.Exec(ctx, upsertUserWithRole,
		arg.ClerkID,
		arg.Username,
		arg.Name,
		arg.Email,
	)
	return err
}
